# Generated by Django 6.0.6 on 2026-06-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_restaurant_orders_restaurant_product_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.restaurant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.restaurant'),
        ),
    ]
