# Generated by Django 6.0.6 on 2026-06-09 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_is_available_product_preparation_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='restaurant_lat',
            field=models.FloatField(default=-6.7924),
        ),
        migrations.AddField(
            model_name='orders',
            name='restaurant_lng',
            field=models.FloatField(default=39.2083),
        ),
        migrations.AddField(
            model_name='orders',
            name='rider_lat',
            field=models.FloatField(default=-6.7924),
        ),
        migrations.AddField(
            model_name='orders',
            name='rider_lng',
            field=models.FloatField(default=39.2083),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Received'), (2, 'Preparing Food'), (3, 'Cooking'), (4, 'Packaging'), (5, 'Rider Assigned'), (6, 'Rider Picked Up Order'), (7, 'Rider En Route'), (8, 'Near Destination'), (9, 'Delivered')], default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_lat',
            field=models.FloatField(default=-6.8),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_lng',
            field=models.FloatField(default=39.22),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notification', max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
