# Generated by Django 6.0.6 on 2026-06-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_configuration_remove_orders_items_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='actor',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.AddField(
            model_name='orders',
            name='items_json',
            field=models.JSONField(default='', help_text='Stores the ordered items in structured JSON format'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
